name: Build Windows (WPF .NET 8)

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Verify project exists
        run: |
          if (-not (Test-Path "src/OperativaLogistica/OperativaLogistica.csproj")) {
            Write-Error "❌ No se encuentra src/OperativaLogistica/OperativaLogistica.csproj. Sube la carpeta completa."
          }

      - name: Restore
        run: dotnet restore src/OperativaLogistica/OperativaLogistica.csproj

      - name: Build
        run: dotnet build src/OperativaLogistica/OperativaLogistica.csproj -c Release --no-restore

      - name: Publish self-contained
        run: dotnet publish src/OperativaLogistica/OperativaLogistica.csproj -c Release -r win-x64 --self-contained true -p:PublishSingleFile=true -o out

      - name: Zip artifact
        run: Compress-Archive -Path out\* -DestinationPath OperativaLogistica-win-x64.zip

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: OperativaLogistica-win-x64
          path: OperativaLogistica-win-x64.zip
