
name: Build Windows (WPF .NET 8)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  build-win:
    runs-on: windows-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8 SDK
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Verify project exists
        shell: pwsh
        run: |
          if (-not (Test-Path "src/OperativaLogistica/OperativaLogistica.csproj")) {
            Write-Error "No se encuentra src/OperativaLogistica/OperativaLogistica.csproj. Sube el proyecto descomprimido respetando la estructura exacta del ZIP."
          }

      - name: Restore
        shell: pwsh
        run: dotnet restore "src/OperativaLogistica/OperativaLogistica.csproj"

      - name: Build (Release)
        shell: pwsh
        run: dotnet build "src/OperativaLogistica/OperativaLogistica.csproj" -c Release --no-restore -p:UseWpf=true

      - name: Publish (self-contained, single file)
        shell: pwsh
        run: >
          dotnet publish "src/OperativaLogistica/OperativaLogistica.csproj"
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -p:PublishTrimmed=false
          -p:UseWpf=true
          -o Publish/win-x64

      - name: Zip published output
        shell: pwsh
        run: |
          Compress-Archive -Path Publish/win-x64/* -DestinationPath OperativaLogistica-win-x64.zip

      - name: Upload artifact (ZIP)
        uses: actions/upload-artifact@v4
        with:
          name: OperativaLogistica-win-x64
          path: OperativaLogistica-win-x64.zip
