name: Build Windows (WPF .NET 8)

on:
  workflow_dispatch:

jobs:
  build-win:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restore dependencies
        run: dotnet restore app-final.sln

      - name: Build solution (Release)
        run: dotnet build app-final.sln -c Release --no-restore -v detailed

      - name: Publish app (self-contained, single file)
        run: >
          dotnet publish app-final.sln
          -c Release
          -r win-x64
          --self-contained true
          -p:PublishSingleFile=true
          -p:IncludeNativeLibrariesForSelfExtract=true
          -p:PublishTrimmed=false
          -o Publish/win-x64
          -v detailed

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: OperativaLogistica-win-x64
          path: Publish/win-x64
